name: Pre-commit auto-update
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update pre-commit hooks"
          add: ".pre-commit-config.yaml"
          default_author: github_actions
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
